learning_rate: 0.0003
max_sequence_length: 50
max_genres: 3
batch_size: 1024
min_sequence_length: 5
max_epochs: 100
patience: 5
n_folds: 3
num_movies: 70000
num_genres: 25
test_size: 0.2
random_seed: 42
checkpoint_path: "checkpoints/early_stop.pt"
final_checkpoint_path: "checkpoints/final.pt"